### PR TITLE
fix common elements count algorithm - Comparison API

### LINKED ISSUE #27: Common elements count algorithm is not correct - Comparison api
I think counting common elements actually shouldn't deduplicate... For example, let's say the arrays `[1,2,1]` and `[1,1,2]` are the lengths arrays for A and B; then `commonLengthsCount` should be 3.  On the other hand if A's array is `[1,2,1]` and B's is `[1,2]`, the common count should be 2, so I think it's slightly more complicated than using `A.retainAll(B)`...

_Originally posted by @apriltuesday in https://github.com/EBIvariation/eva-seqcol/pull/21#discussion_r1291105096_

### PR DESCRIPTION
**Pull request by waterflow80**
closes #27

### CODE REVIEW

File: src/main/java/uk/ac/ebi/eva/evaseqcol/service/SeqColService.java [hunk 1]
```diff
@@ -298,6 +295,30 @@ public List<String> getCommonFieldsDistinct(List<String> seqColAFields, List<Str
         return commonFieldsDistinct;
     }
 
+    /**
+     * Return the number of common elements between listA and listB
+     * Note: Time complexity for this method is about O(n²)*/
+    public Integer getCommonElementsCount(List<String> listA, List<String> listB) {
```
Comment (apriltuesday) [inline src/main/java/uk/ac/ebi/eva/evaseqcol/service/SeqColService.java:301]: This looks correct to me, just need to call it in the compare method!

Comment (waterflow80) [reply src/main/java/uk/ac/ebi/eva/evaseqcol/service/SeqColService.java:301]: Done
