### PR TITLE
Digest algorithm correction - level 2 to level 1 digest calculation

### LINKED ISSUE #32: Using the wrong algorithm to digest seqCol Level 2 into Level 1 seqCol object
Currently we're using the [SHA512ChecksumCalculator](https://github.com/EBIvariation/eva-seqcol/blob/8212eee1972f9eef8b6d58a11915b9b09b57c217/src/main/java/uk/ac/ebi/eva/evaseqcol/refget/SHA512ChecksumCalculator.java#L23) to digest `seqColLevelTwo` into `Level one object`, which not quite correct.
We should be using the [DigestCalculator](https://github.com/EBIvariation/eva-seqcol/blob/8212eee1972f9eef8b6d58a11915b9b09b57c217/src/main/java/uk/ac/ebi/eva/evaseqcol/digests/DigestCalculator.java#L11C14-L11C30) instead.

### PR DESCRIPTION
**Pull request by waterflow80**
closes #32

### CODE REVIEW

File: src/main/java/uk/ac/ebi/eva/evaseqcol/entities/SeqColExtendedDataEntity.java [hunk 1]
```diff
@@ -164,10 +166,10 @@ public static SeqColExtendedDataEntity constructSeqColSortedNameLengthPairs(
         // Get the sorted list
         List<String> sortedNameLengthPairsList = constructSortedNameLengthPairs(nameLengthPairList);
```
Comment (apriltuesday) [inline src/main/java/uk/ac/ebi/eva/evaseqcol/entities/SeqColExtendedDataEntity.java:167]: Think you missed the one in `constructSortedNameLengthPairs` (lines 192+), it's still `SHA512ChecksumCalculator` rather than `DigestCalculator`

Comment (waterflow80) [reply src/main/java/uk/ac/ebi/eva/evaseqcol/entities/SeqColExtendedDataEntity.java:167]: True, I'll fix it

**Review by apriltuesday — APPROVED** [review]

**Review by sundarvenkata-EBI — APPROVED** [review]

**Review by tcezard — APPROVED** [review]
